name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "PRIVATE_KEY=${{ secrets.MY_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "CERTIFICATE=${{ secrets.MY_CERTIFICATE }}" >> $GITHUB_ENV


      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build-dev

      - name: Deploy
        run: npm run start-dev
